In [1]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords
import string

In [2]:
df = pd.read_csv("HIFIS_Clients_example.csv")

df.head()

,ClientID,PersonID,ConsentType,FamilyID,RelationshipType,DOB,CurrentAge,Gender,AboriginalIndicator,Citizenship,...,DietCatetory,FoodType,AvoidedDietYN,IntakeID,PreScreenPeriod,TotalScore,ClientBarredPeriodID,Reason,Modules,ServiceRestricitonOrganizationName
0,0,0,Declined - Anonymous,NaN,NaN,1973-08-23 0:00,47,Male,Non-Indigenous,Canadian Citizen - Born in Canada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,Declined - Anonymous,NaN,NaN,1973-08-23 0:00,47,Male,Non-Indigenous,Canadian Citizen - Born in Canada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df.columns.tolist())

['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType', 'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship', 'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth', 'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG', 'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart', 'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType', 'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount', 'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel', 'EducationStartDate', 'EducationEndDate', 'HealthIssueID', 'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN', 'HealthIssuesMedicationName', 'OtherMedications', 'clientContributingFactorID', 'ContributingFactor', 'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity', 'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory', 'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod', 'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules', 'ServiceRestricitonOrganizationName']

In [7]:
print(df.columns)

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')

In [8]:
list(df.columns)

['ClientID',
 'PersonID',
 'ConsentType',
 'FamilyID',
 'RelationshipType',
 'DOB',
 'CurrentAge',
 'Gender',
 'AboriginalIndicator',
 'Citizenship',
 'VeteranStatus',
 'CountryOfBirth',
 'ProvinceOfBirth',
 'CityOfBirth',
 'EyeColour',
 'HairColour',
 'ClientHeightCM',
 'ClientWeightKG',
 'InHousing',
 'MovedInDate',
 'ServiceID',
 'ServiceType',
 'DateStart',
 'DateEnd',
 'ReasonForService',
 'OrganizationName',
 'IncomeType',
 'MonthlyAmount',
 'ClientExpenseID',
 'ExpenseType',
 'ExpenseAmount',
 'ExpenseFrequency',
 'IsEssentialYN',
 'EducationLevel',
 'EducationStartDate',
 'EducationEndDate',
 'HealthIssueID',
 'HealthIssue',
 'DiagnosedYN',
 'SelfReportedYN',
 'SuspectedYN',
 'HealthIssuesMedicationName',
 'OtherMedications',
 'clientContributingFactorID',
 'ContributingFactor',
 'ClientBehaviouralFactorID',
 'BehavioralFactor',
 'Severity',
 'PeopleLifeEventID',
 'LifeEvent',
 'ClientDietID',
 'DietCatetory',
 'FoodType',
 'AvoidedDietYN',
 'IntakeID',
 'PreScreenPeriod',
 'TotalScore',
 'ClientBarredPeriodID',
 'Reason',
 'Modules',
 'ServiceRestricitonOrganizationName']

In [10]:
df.columns = df.columns.str.strip()

In [14]:
print(df.columns)

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')

In [17]:
df.head()

Empty DataFrame
Columns: [ClientID, PersonID, ConsentType, FamilyID, RelationshipType, DOB, CurrentAge, Gender, AboriginalIndicator, Citizenship, VeteranStatus, CountryOfBirth, ProvinceOfBirth, CityOfBirth, EyeColour, HairColour, ClientHeightCM, ClientWeightKG, InHousing, MovedInDate, ServiceID, ServiceType, DateStart, DateEnd, ReasonForService, OrganizationName, IncomeType, MonthlyAmount, ClientExpenseID, ExpenseType, ExpenseAmount, ExpenseFrequency, IsEssentialYN, EducationLevel, EducationStartDate, EducationEndDate, HealthIssueID, HealthIssue, DiagnosedYN, SelfReportedYN, SuspectedYN, HealthIssuesMedicationName, OtherMedications, clientContributingFactorID, ContributingFactor, ClientBehaviouralFactorID, BehavioralFactor, Severity, PeopleLifeEventID, LifeEvent, ClientDietID, DietCatetory, FoodType, AvoidedDietYN, IntakeID, PreScreenPeriod, TotalScore, ClientBarredPeriodID, Reason, Modules, ServiceRestricitonOrganizationName]
Index: []

[0 rows x 61 columns]

In [19]:
print(df.columns)

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')

In [22]:
print(df.columns)

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')

In [26]:
print(df.columns)
plt.show()

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')

In [28]:
df.columns = df.columns.str.strip()

In [29]:
df.head()

Empty DataFrame
Columns: [ClientID, PersonID, ConsentType, FamilyID, RelationshipType, DOB, CurrentAge, Gender, AboriginalIndicator, Citizenship, VeteranStatus, CountryOfBirth, ProvinceOfBirth, CityOfBirth, EyeColour, HairColour, ClientHeightCM, ClientWeightKG, InHousing, MovedInDate, ServiceID, ServiceType, DateStart, DateEnd, ReasonForService, OrganizationName, IncomeType, MonthlyAmount, ClientExpenseID, ExpenseType, ExpenseAmount, ExpenseFrequency, IsEssentialYN, EducationLevel, EducationStartDate, EducationEndDate, HealthIssueID, HealthIssue, DiagnosedYN, SelfReportedYN, SuspectedYN, HealthIssuesMedicationName, OtherMedications, clientContributingFactorID, ContributingFactor, ClientBehaviouralFactorID, BehavioralFactor, Severity, PeopleLifeEventID, LifeEvent, ClientDietID, DietCatetory, FoodType, AvoidedDietYN, IntakeID, PreScreenPeriod, TotalScore, ClientBarredPeriodID, Reason, Modules, ServiceRestricitonOrganizationName]
Index: []

[0 rows x 61 columns]

In [30]:
df.columns

Index(['ClientID', 'PersonID', 'ConsentType', 'FamilyID', 'RelationshipType',
       'DOB', 'CurrentAge', 'Gender', 'AboriginalIndicator', 'Citizenship',
       'VeteranStatus', 'CountryOfBirth', 'ProvinceOfBirth', 'CityOfBirth',
       'EyeColour', 'HairColour', 'ClientHeightCM', 'ClientWeightKG',
       'InHousing', 'MovedInDate', 'ServiceID', 'ServiceType', 'DateStart',
       'DateEnd', 'ReasonForService', 'OrganizationName', 'IncomeType',
       'MonthlyAmount', 'ClientExpenseID', 'ExpenseType', 'ExpenseAmount',
       'ExpenseFrequency', 'IsEssentialYN', 'EducationLevel',
       'EducationStartDate', 'EducationEndDate', 'HealthIssueID',
       'HealthIssue', 'DiagnosedYN', 'SelfReportedYN', 'SuspectedYN',
       'HealthIssuesMedicationName', 'OtherMedications',
       'clientContributingFactorID', 'ContributingFactor',
       'ClientBehaviouralFactorID', 'BehavioralFactor', 'Severity',
       'PeopleLifeEventID', 'LifeEvent', 'ClientDietID', 'DietCatetory',
       'FoodType', 'AvoidedDietYN', 'IntakeID', 'PreScreenPeriod',
       'TotalScore', 'ClientBarredPeriodID', 'Reason', 'Modules',
       'ServiceRestricitonOrganizationName'],
      dtype='str')